apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
spec:
  selector:
    matchLabels:
      app: mypod
  template: 
    metadata:
      labels:
        app: mypod
    spec:
      containers:
        - name: site
          image: fabricioveronez/web-page:blue
          ports:
            - containerPort: 80  